export const TipoFormEnum = {
    HIDDEN: "hidden",
    TEXT_INPUT: "TextInput",
    SELECT_INPUT: "SelectInput",
    BINARIO_INPUT: "BinarioInput",
    EDITOR_INPUT: "EditorInput",
    EMAIL_INPUT: "EmailInput",
    DATE_INPUT: "DateInput",
    TABLE_SELECT_INPUT: "TableSelectInput",
    KANBAN_FORM: "KanbanForm",
    HIDDEN_INT: "hiddenInt",
    NUMBER_INPUT: "NumberInput",
    MONEY_INPUT: "MoneyInput",
    LABEL: "label",
    LB_LIST: "lbList",
    LB_KANBAN: "kanbanList",
    TITLE_H5: "titleH5",
    TITLE_P: "titleP",
    TITLE_SMALL: "titleSmall",
    BUTTON: "Button",
    LABEL_INPUT: "LabelInput",
    TABLE_INPUT: "TableInput",
    LB_TABLE: "TableLabel",
};

